name: build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows'
            os: windows-2019
            vcpkg_dir: 'C:\vcpkg'
            generator: 'Visual Studio 16 2019'
          - name: 'Linux x64'
            os: ubuntu-latest
            vcpkg_dir: '/usr/local/share/vcpkg'
            generator: 'Unix Makefiles'
          - name: 'Mac OSX'
            os: macos-latest
            vcpkg_dir: '/usr/local/share/vcpkg'
            generator: 'Unix Makefiles'

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install vcpkg packages
        shell: bash
        run: |
          vcpkg install cpr
          vcpkg integrate install

      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir install
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake \
              -B ./build \
              -G "${{ matrix.generator }}" \
              .
          else
            if [ "$RUNNER_OS" == "Linux" ]; then
              export CC=/usr/bin/gcc-9
              export CXX=/usr/bin/g++-9
            fi
            cmake \
              -B ./build \
              -G "${{ matrix.generator }}" \
              .
          fi

      - name: Compile
        shell: bash
        run: cmake --build ./build --target Yoomoney --config Realese
